# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
